# Generated by Django 5.2.8 on 2025-11-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('tweets_collected', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('tweet_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='scraper_twe_timesta_abd218_idx'), models.Index(fields=['content_hash'], name='scraper_twe_content_97681b_idx'), models.Index(fields=['username'], name='scraper_twe_usernam_82e96c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TweetSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vector', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('custom_features', models.JSONField(blank=True, default=dict)),
                ('composite_signal', models.FloatField(blank=True, null=True)),
                ('confidence_interval_lower', models.FloatField(blank=True, null=True)),
                ('confidence_interval_upper', models.FloatField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='scraper.tweet')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['-composite_signal'], name='scraper_twe_composi_6ddaa8_idx'), models.Index(fields=['sentiment_score'], name='scraper_twe_sentime_61aebc_idx')],
            },
        ),
    ]
